//
//  MusapModule.mm
//  musap-react-native
//
//  Objective-C++ TurboModule implementation
//  This file bridges between React Native C++ TurboModules and the Swift facade
//

#import "MusapModule.h"

// Import the Swift-generated header
// This header is auto-generated by Xcode when Swift code is compiled with @objc
#if __has_include("musap_react_native-Swift.h")
    #import "musap_react_native-Swift.h"
#else
    // Fallback for when the header is not yet generated
    @class MusapBridge;
#endif

@implementation MusapModule

- (instancetype)init {
    if (self = [super init]) {
        // Initialization if needed
    }
    return self;
}

// MARK: - SSCD Management

- (void)enableSscd:(NSString *)sscdType
            sscdId:(NSString * _Nullable)sscdId
          settings:(NSDictionary * _Nullable)settings
           resolve:(void (^)(id _Nullable result))resolve
            reject:(void (^)(NSString *code, NSString *message, NSError * _Nullable error))reject {

    // Get the shared Swift bridge instance
    MusapBridge *bridge = [MusapBridge shared];

    // Call the Swift facade with a completion handler
    [bridge enableSscd:sscdType
                sscdId:sscdId
              settings:settings
            completion:^(BOOL success, NSDictionary * _Nullable errorDict) {
        if (success) {
            // Resolve with null for void return
            resolve(nil);
        } else {
            // Extract error information from the dictionary
            NSString *code = errorDict[@"code"] ?: @"UNKNOWN_ERROR";
            NSString *message = errorDict[@"message"] ?: @"An unknown error occurred";

            // Create NSError
            NSError *error = [NSError errorWithDomain:@"com.sphereon.musaprn"
                                                 code:-1
                                             userInfo:@{NSLocalizedDescriptionKey: message}];
            reject(code, message, error);
        }
    }];
}

- (NSArray *)listEnabledSscds {
    MusapBridge *bridge = [MusapBridge shared];
    return [bridge listEnabledSscds];
}

- (NSArray *)listActiveSscds {
    MusapBridge *bridge = [MusapBridge shared];
    return [bridge listActiveSscds];
}

// MARK: - Key Management

- (void)generateKey:(NSString *)sscdId
            request:(NSDictionary *)request
            resolve:(void (^)(NSString *keyUri))resolve
             reject:(void (^)(NSString *code, NSString *message, NSError * _Nullable error))reject {

    MusapBridge *bridge = [MusapBridge shared];

    [bridge generateKey:sscdId
                request:request
             completion:^(NSString * _Nullable keyUri, NSDictionary * _Nullable errorDict) {
        if (keyUri) {
            resolve(keyUri);
        } else {
            NSString *code = errorDict[@"code"] ?: @"UNKNOWN_ERROR";
            NSString *message = errorDict[@"message"] ?: @"An unknown error occurred";

            NSError *error = [NSError errorWithDomain:@"com.sphereon.musaprn"
                                                 code:-1
                                             userInfo:@{NSLocalizedDescriptionKey: message}];
            reject(code, message, error);
        }
    }];
}

- (NSArray *)listKeys {
    MusapBridge *bridge = [MusapBridge shared];
    return [bridge listKeys];
}

- (NSDictionary * _Nullable)getKeyByUri:(NSString *)keyUri {
    MusapBridge *bridge = [MusapBridge shared];
    return [bridge getKeyByUri:keyUri];
}

// MARK: - Signature Operations

- (void)sign:(NSDictionary *)request
     resolve:(void (^)(NSString *signature))resolve
      reject:(void (^)(NSString *code, NSString *message, NSError * _Nullable error))reject {

    MusapBridge *bridge = [MusapBridge shared];

    [bridge sign:request
      completion:^(NSString * _Nullable signature, NSDictionary * _Nullable errorDict) {
        if (signature) {
            resolve(signature);
        } else {
            NSString *code = errorDict[@"code"] ?: @"UNKNOWN_ERROR";
            NSString *message = errorDict[@"message"] ?: @"An unknown error occurred";

            NSError *error = [NSError errorWithDomain:@"com.sphereon.musaprn"
                                                 code:-1
                                             userInfo:@{NSLocalizedDescriptionKey: message}];
            reject(code, message, error);
        }
    }];
}

// MARK: - Link Management

- (NSString * _Nullable)getLink {
    MusapBridge *bridge = [MusapBridge shared];
    return [bridge getLink];
}

- (void)enableLink:(NSString *)url
          fcmToken:(NSString * _Nullable)fcmToken
           resolve:(void (^)(NSString *musapId))resolve
            reject:(void (^)(NSString *code, NSString *message, NSError * _Nullable error))reject {

    MusapBridge *bridge = [MusapBridge shared];

    [bridge enableLink:url
              fcmToken:fcmToken
            completion:^(NSString * _Nullable musapId, NSDictionary * _Nullable errorDict) {
        if (musapId) {
            resolve(musapId);
        } else {
            NSString *code = errorDict[@"code"] ?: @"UNKNOWN_ERROR";
            NSString *message = errorDict[@"message"] ?: @"An unknown error occurred";

            NSError *error = [NSError errorWithDomain:@"com.sphereon.musaprn"
                                                 code:-1
                                             userInfo:@{NSLocalizedDescriptionKey: message}];
            reject(code, message, error);
        }
    }];
}

@end

/**
 * IMPORTANT NOTES FOR TURBOMODULE INTEGRATION:
 *
 * 1. This is a basic Objective-C++ implementation showing the bridge pattern.
 *    For full TurboModule support in React Native 0.79, you need to:
 *    - Create a TurboModule spec (TypeScript interface)
 *    - Run Codegen to generate C++ headers
 *    - Implement the generated TurboModule interface (e.g., NativeMusapModuleSpec)
 *
 * 2. The Swift facade (MusapBridge.swift) handles:
 *    - Accepting simple Objective-C types (NSString, NSDictionary, etc.)
 *    - Converting to complex Swift types internally
 *    - Calling the upstream musap-ios Swift library
 *    - Returning results via completion blocks with simple types
 *
 * 3. This .mm file handles:
 *    - Implementing the TurboModule interface (or basic module interface)
 *    - Calling the Swift facade
 *    - Converting between C++/Objective-C++ and Objective-C types
 *    - Handling promises and callbacks
 *
 * 4. Architecture Flow:
 *    JavaScript → C++ TurboModule → Objective-C++ (this file) → Swift facade → musap-ios
 *
 * 5. Key Benefits:
 *    - Avoids Swift C++ interop issues (uses mature Objective-C ↔ Swift interop)
 *    - No changes needed in upstream musap-ios library
 *    - Clean separation of concerns
 *    - Compatible with React Native 0.79 New Architecture
 */
